sudo: required
services:
  - docker


before_install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose down

after_success:
  - docker build -t oseun/sterlin-nginx  ./nginx
  - docker build -t oseun/sterlin-server  .


# Login to Docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# Take images and push them to dockerhub

  - docker push oseun/sterlin-nginx
  - docker push oseun/sterlin-server




# Sterling

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: sterlin
  env: Sterlin-env 
  bucket_name: elasticbeanstalk-us-east-2-632874205370
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"